[metadata]
name = morse-lang
version = 1.0.0
author = Your Name
author_email = you@example.com
description = Morse programming language
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/sharky-3/morse-programming-language
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.9

[options.entry_points]
console_scripts =
    morse = app:main
